CREATE DATABASE BlogDB;
USE BlogDB;
CREATE TABLE PROJECT (
    PROJECT_ID AUTO_INCREMENT  PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTON TEXT,
    DATE-DéB DATE,
    DATE-FIN DATE,
    STATUS VARCHAR(50),
      idEmp INT NOT NULL,  
      FOREIGN KEY (idEmp) REFERENCES Employe(idEmp)
);
 CREATE TABLE TACHE (
    TACHE_ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTON TEXT NOT NULL,
    DATE-LIMITE DATE,
    éTAT VARCHAR(50),
    PRIORITE VARCHAR(50),
    ID-PROJECT INT NOT NULL,
    idEmp INT NOT NULL,
    FOREIGN KEY (ID-PROJECT)REFERENCES PROJECT(PROJECT_ID),
    FOREIGN KEY (idEmp)REFERENCES Employe(idEmp),
 );
   CREATE TABLE Employe (
    idEmp INT PRIMARY KEY AUTO_INCREMENT,
    NOM VARCHAR(100) NOT NULL,
    PRéNOM VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    ROLE VARCHAR(50)
   );
   
 



